# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{scene-toolkit}
  s.version = "0.1.7"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["V\303\255ctor Mart\303\255nez"]
  s.date = %q{2011-01-14}
  s.default_executable = %q{scene-toolkit}
  s.description = %q{Tool to assist scene MP3 library maintenance}
  s.email = %q{knoopx@gmail.com}
  s.executables = ["scene-toolkit"]
  s.extra_rdoc_files = [
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/scene-toolkit",
    "lib/scene_toolkit.rb",
    "lib/scene_toolkit/cli.rb",
    "lib/scene_toolkit/ext.rb",
    "lib/scene_toolkit/ext/hash.rb",
    "lib/scene_toolkit/release.rb"
  ]
  s.homepage = %q{http://github.com/knoopx/scene-toolkit}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Tool to assist scene MP3 library maintenance}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_runtime_dependency(%q<i18n>, ["~> 0.5.0"])
      s.add_runtime_dependency(%q<rainbow>, ["~> 1.1"])
      s.add_runtime_dependency(%q<optitron>, ["~> 0.2.2"])
    else
      s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
      s.add_dependency(%q<i18n>, ["~> 0.5.0"])
      s.add_dependency(%q<rainbow>, ["~> 1.1"])
      s.add_dependency(%q<optitron>, ["~> 0.2.2"])
    end
  else
    s.add_dependency(%q<activesupport>, ["~> 3.0.0"])
    s.add_dependency(%q<i18n>, ["~> 0.5.0"])
    s.add_dependency(%q<rainbow>, ["~> 1.1"])
    s.add_dependency(%q<optitron>, ["~> 0.2.2"])
  end
end

